"""add slack_threads table

Revision ID: 4c7b27071440
Revises: 
Create Date: 2026-03-20 12:58:05.655372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c7b27071440'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slack_threads',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slack_channel_id', sa.String(length=64), nullable=False),
    sa.Column('slack_thread_ts', sa.String(length=64), nullable=False),
    sa.Column('slack_user_id', sa.String(length=64), nullable=False),
    sa.Column('langgraph_thread_id', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('langgraph_thread_id'),
    sa.UniqueConstraint('slack_channel_id', 'slack_thread_ts', name='uq_channel_thread')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('slack_threads')
    # ### end Alembic commands ###
