"""add user_queries table

Revision ID: b69168299f32
Revises: 4c7b27071440
Create Date: 2026-03-20 15:05:32.652778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b69168299f32'
down_revision: Union[str, Sequence[str], None] = '4c7b27071440'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slack_threads',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slack_channel_id', sa.String(length=64), nullable=False),
    sa.Column('slack_thread_ts', sa.String(length=64), nullable=False),
    sa.Column('slack_user_id', sa.String(length=64), nullable=False),
    sa.Column('langgraph_thread_id', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('langgraph_thread_id'),
    sa.UniqueConstraint('slack_channel_id', 'slack_thread_ts', name='uq_channel_thread')
    )
    op.create_table('user_queries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slack_thread_id', sa.Uuid(), nullable=False),
    sa.Column('slack_user_id', sa.String(length=64), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['slack_thread_id'], ['slack_threads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_queries_slack_thread_id', 'user_queries', ['slack_thread_id'], unique=False)
    op.create_index('idx_user_queries_user_status', 'user_queries', ['slack_user_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_queries_user_status', table_name='user_queries')
    op.drop_index('idx_user_queries_slack_thread_id', table_name='user_queries')
    op.drop_table('user_queries')
    op.drop_table('slack_threads')
    # ### end Alembic commands ###
